.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH "LSAT PREP" 1 "July 3, 2026"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
lsat-prep \- professional LSAT preparation software
.SH DESCRIPTION
\fBLSAT Prep\fP is a focused study system for the Law School Admission Test.
It combines evidence-earned scores that never overstate what you have proven,
oracle-verified formal-logic drills, spaced-repetition review, and diagnostics
that show exactly how you get questions wrong \- so every study minute is spent
on the material that will move your score.

LSAT Prep is built on a spaced-repetition engine: each time you review some
material, you wait longer than last time before reviewing it again. This
maximizes the time spent on difficult material and minimizes time spent on
things you already know.

.SH OPTIONS
.B \-b <dir>
Use <dir> as the base folder instead of the default

.B \-p ProfileName
Load a specific profile

.B \-l <lang>
Start the program in a specific language (de=German, en=English, etc)
.SH SEE ALSO
LSAT Prep home page: <https://lsatprep.app/>
.SH AUTHOR
LSAT Prep is built on the open-source Anki spaced-repetition engine
(\fIhttps://apps.ankiweb.net\fP), licensed under the GNU AGPL v3.
